### PR TITLE
[share] Allowing shared images on iOS to have specific actions (save …

### PR DESCRIPTION
**Pull request by aloisdeniel**
## Description

When sharing an image from an iOS app, there are more options available.

image

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jagmit** [comment]
Really like this feature. 
@pboos since your PR developed a life on it's own anyways because of Flutter team's (presumably) unwillingness to merge it do you mind accepting this PR (maybe into a branch that is separate to your merge attempt to the official flutter/plugins)?

**Comment by pboos** [comment]
Thank you! Sorry that it took so long to merge. Looked good to me, so I merged it :).

**Comment by pboos** [comment]
@aloisdeniel Can you follow the instructions in https://github.com/flutter/plugins/pull/970#issuecomment-644872920 to give your consent for using your code in flutter? Thanks :)

**Comment by aloisdeniel** [comment]
@googlebot I consent.

**Comment by pboos** [comment]
@aloisdeniel You actually have to do this in the other PR ;-)

**Pull request merged**
